import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nakson Services",
  description: "Generated by create next app",
  image: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/app/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" sizes="180x180" href="/app/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="/app/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/app/favicon-16x16.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/app/app/android-chrome-192x192.png"/>

      </head>
      <AuthProvider>
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
